
[font.normal]
family = "GeistMono NF"
style = "Regular"

[font]
size = 10.0

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/bin/zsh"

[window]
startup_mode = "Maximized"
padding = { x = 10, y = 0 }

[general]
live_config_reload = true

