
[font.normal]
family = "GeistMono NF"
style = "Regular"

[font]
size = 8.0

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/bin/zsh"

[window]
startup_mode = "Maximized"

[general]
live_config_reload = true

[terminal]
