# See https://docs.rs/i3status-rs/latest/i3status_rs/blocks/index.html

icons_format = "{icon}"

[theme]
theme = "solarized-dark"

[theme.overrides]

[icons]
icons = "awesome4"

[[block]]
block = "net"
format = " $device $ip "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $percentage.eng(w:2) "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "

[[block]]
block = "battery"
device = "BAT1"
format = " $icon $percentage.eng(w:2) "

# [[block]]
# block = "sound"
# [[block.click]]
# button = "left"
# cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%R') "