# https://taskfile.dev

version: "3"

vars:
  remote: root@shire.bear-antares.ts.net
  dir: /home/jack

tasks:
  sync:
    desc: Syncs Caddy, Docker and the homepage
    deps:
      - caddy
      - docker
    cmds:
      - rsync -avu --delete ./site/ {{.remote}}:/srv/

  caddy:
    desc: Sync and reload Caddy
    cmds:
      - rsync ./Caddyfile {{.remote}}:/etc/caddy/Caddyfile
      - ssh {{.remote}} "systemctl reload caddy"

  docker:
    desc: Sync and reload Docker
    cmds:
      - rsync ./docker-compose.yml {{.remote}}:{{.dir}}/docker-compose.yml
      - ssh {{.remote}} "docker compose -f {{.dir}}/docker-compose.yml up -d"

  update:
    desc: Update system dependencies and Docker containers
    cmds:
      - ssh {{.remote}} "sudo apt update && sudo apt upgrade -y"
      - ssh {{.remote}} "docker compose -f {{.dir}}/docker-compose.yml pull && docker compose -f {{.dir}}/docker-compose.yml up -d"

  kick:
    desc: Restart everything
    cmds:
      - ssh {{.remote}} "docker compose -f {{.dir}}/docker-compose.yml restart"
      - ssh {{.remote}} "systemctl restart caddy"

  status:
    desc: Prints the remote's IP and containers.
    cmds:
      - ssh {{.remote}} "fastfetch"
