# https://taskfile.dev

version: "3"

vars:
  remote: root@shire.bear-antares.ts.net
  dir: /home/jack

tasks:
  sync:
    desc: Syncs Caddy, Docker and the homepage
    deps:
      - caddy
      - site
      - docker

  caddy:
    desc: Sync and reload Caddy
    cmds:
      - rsync ./Caddyfile {{.remote}}:/etc/caddy/Caddyfile
      - ssh {{.remote}} "bash -c 'systemctl reload caddy'"

  site:
    desc: Sync the homepage website to /srv
    cmds:
      - rsync -avu --delete ./site/ {{.remote}}:/srv/

  docker:
    desc: Sync and reload Docker
    cmds:
      - rsync ./docker-compose.yml {{.remote}}:{{.dir}}/docker-compose.yml
      - ssh {{.remote}} "bash -c 'docker compose -f {{.dir}}/docker-compose.yml up -d'"

  update:
    desc: Update system dependencies and Docker containers
    cmds:
      - ssh {{.remote}} "sudo apt update && sudo apt upgrade -y"
      - ssh {{.remote}} "docker compose -f {{.dir}}/docker-compose.yml pull && docker compose -f {{.dir}}/docker-compose.yml up -d"

  kick:
    desc: Restart everything
    cmds:
      - ssh {{.remote}} "docker compose -f {{.dir}}/docker-compose.yml restart"
      - ssh {{.remote}} "systemctl restart caddy"

  couchdb:
    cmds:
      - ssh {{.remote}} "hostname=localhost:5984 username=root password=root bash -c 'echo $hostname && curl -s https://raw.githubusercontent.com/vrtmrz/obsidian-livesync/main/utils/couchdb/couchdb-init.sh | bash'"

  status:
    vars:
      docker_format: "{{ `id: {{ .ID }}, name: {{ .Names }}, image: {{ .Image }}` }}"
    cmds:
      - ssh {{.remote}} "hostname -I"
      - ssh {{.remote}} "docker ps --format '{{.docker_format}}'"
