---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Services:
    - Actual:
        href: https://actual.shire.network
        siteMonitor: https://actual.shire.network
        icon: actual-budget

    - Jellyfin:
        href: https://jellyfin.shire.network
        siteMonitor: https://jellyfin.shire.network
        icon: jellyfin

    - Beszel:
        href: https://status.shire.network
        siteMonitor: https://status.shire.network
        icon: beszel

    - Files:
        href: https://files.shire.network
        siteMonitor: https://files.shire.network
        icon: files

    - CouchDB (Obsidian):
        href: https://couchdb.shire.network/_utils/
        siteMonitor: https://couchdb.shire.network/
        icon: couchdb
